version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: BuildingBlocks/Docker/Dockerfile.service
      target: tsconfig
      args:
        port: 8080
        service_path: ApiGateway
    networks:
      - internal
      - external
  exchange:
    build:
      context: .
      dockerfile: BuildingBlocks/Docker/Dockerfile.service
      target: base
      args:
        port: 9000
        service_path: Services/Exchange
    env_file:
      - ./BuildingBlocks/Envs/exchanger.env
    networks:
      - internal
  users:
    build:
      context: .
      dockerfile: BuildingBlocks/Docker/Dockerfile.service
      target: base
      args:
        port: 9001
        service_path: Services/Users
    networks:
      - internal
networks:
  internal:
    name: internal
  external:
    name: external