import { Button, Card } from 'flowbite-react'
import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <>
      <Head>
        <title>Exchanger</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="h-screen w-screen flex justify-center items-center">
          <Card className='p-8'>
            <h1 className='text-2xl'>Login or SignUp</h1>
            <Button href='/login'>Login</Button>
            <Button href='/signup'>Signup</Button>
          </Card>
        </div>
      </main>
    </>
  )
}
